#!/usr/bin/env python
import os
import sys

import torch
from diffusers import DiffusionPipeline

# append project directory to path so predict.py can be imported
sys.path.append('.')

from predict import MODEL_CACHE, MODEL_NAME

# Make cache folder
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

pipe = DiffusionPipeline.from_pretrained(
    MODEL_NAME,
    cache_dir=MODEL_CACHE,
    torch_dtype=torch.float16,
    custom_pipeline=MODEL_NAME
)